name: ENGINE-CONTABLE
on:
  schedule:
    - cron: '*/5 * * * *' # Cada 5 min (Para ver trades rápido)
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: pip install mysql-connector-python requests binance-connector binance-futures-connector python-binance pycryptodome
      - name: Run
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        working-directory: ./pythonProject  
        run: python loader_contable.py